# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe1213b207d6d8f46964d7df091ba2b8ce0807d47566030ef5db04fc4ce319568a9c077a38217f258350d40fa69a816a1c336718de74dce11e72cee8be60694

test:
  secret_key_base: 634d2494e617e63f1940f53d0d389ffc17c71270e5ae99afaea5556e811680b83cb44e1dc6b74aef150eddb0128e40734d97a87ccc8d2320881defcde2922196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
